version: "3"
services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:15.2-alpine
    volumes:
      - ./etc/postgres_data/psql:/var/lib/postgresql/data
      - ./PaperPal-Backend/src/database/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=${TZ}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
      
  backend:
    container_name: ${BACKEND_HOST}
    build: ./PaperPal-Backend
    depends_on:
      - db
    environment:
      - DOMAIN=${DOMAIN}
      - PORT=${BACKEND_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - EMAIL_USER=${EMAIL_USER}
      - OAUTH_CLIENTID=${OAUTH_CLIENTID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_REFRESH_TOKEN=${OAUTH_REFRESH_TOKEN}
      - TZ=${TZ}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./etc/certbot:/var/www/certbot
      - fe-build:/app/dist
    environment:
      - NGINX_DOMAIN=${DOMAIN}
      - NGINX_BACKEND_HOST=${BACKEND_HOST}
      - NGINX_BACKEND_PORT=${BACKEND_PORT}

  frontend:
    depends_on:
      - nginx
    build: ./PaperPal-Frontend
    volumes:
      - fe-build:/app/dist
      
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
    - ./etc/letsencrypt:/etc/letsencrypt
    - ./etc/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  fe-build: